services:
  # Unified Service (Backend + Frontend)
  - type: web
    name: investia-platform
    env: python
    buildCommand: pip install -r backend/requirements.txt && python -m textblob.download_corpora && python backend/train.py --all
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_RECIPIENT
        sync: false

